- name: Create freesurfer directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/quarantine/freesurfer-6.0.0
    - /opt/quarantine/freesurfer-7.1.0

- name: install freesurfer 6.0.0
  unarchive:
    src: https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz
    dest: /opt/quarantine/freesurfer-6.0.0
    creates: /opt/quarantine/freesurfer-6.0.0/freesurfer
    remote_src: yes

- name: install freesurfer 7.1.0
  unarchive:
    src: https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.1.0/freesurfer-linux-centos7_x86_64-7.1.0.tar.gz
    dest: /opt/quarantine/freesurfer-7.1.0
    creates: /opt/quarantine/freesurfer-7.1.0/freesurfer
    remote_src: yes

- name: enable freesurfer 7.1.0
  lineinfile:
    path: /etc/profile.d/99freesurfer-7.1.0.sh
    line: "export FREESURFER_HOME=/opt/quarantine/freesurfer-7.1.0/freesurfer && . ${FREESURFER_HOME}/SetUpFreeSurfer.sh"
    create: yes

- name: install freesurfer licence
  copy: src=files/license.txt dest="{{ item }}"
  loop:
      - /opt/quarantine/freesurfer-7.1.0/freesurfer
      - /opt/quarantine/freesurfer-6.0.0/freesurfer
  ignore_errors: yes
